language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
notifications:
  email:
    on_success: never
    on_failure: never
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install bs4
  - pip install requests
  - pip install lxml
  - pip install tqdm
script:
  - python tests/test_lc.py

